### ISSUE TITLE
[Bug]  line_item_history can have duplicate IDs

### ISSUE THREAD

**Issue by DylanNWatt** [fivetran/dbt_recurly_source#8] opened 2023-02-10 17:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

After reaching out to Fivetran support, I was directed to make a ticket here.

Currently this package has a test expecting  line_item_history to have unique ids. According to fivetran support, that is not the case, attaching the response below.

> I understand that you are seeing duplicate ids in the recurly.line_item_history table. This is expected behaviour as history tables will capture versions of the objects as they are updated. Whenever a line item is updated, instead of updating the existing record in the table, the connector will add a new record for the line item id with the updated values. So the table will have the history of changes to the line item.

### Relevant error log or model output

```shell
17:19:43  Finished running 51 tests in 0 hours 0 minutes and 15.34 seconds (15.34s).
17:19:43  
17:19:43  Completed with 2 errors and 0 warnings:
17:19:43  
17:19:43  Failure in test unique_recurly__balance_transactions_balance_transaction_id (models/recurly.yml)
17:19:43    Got 717 results, configured to fail if != 0
17:19:43  
17:19:43    compiled Code at target/compiled/recurly/models/recurly.yml/unique_recurly__balance_transactions_balance_transaction_id.sql
17:19:43  
17:19:43  Failure in test dbt_utils_unique_combination_of_columns_stg_recurly__invoice_coupon_redemption_history_coupon_redemption_id__invoice_updated_at (models/stg_recurly.yml)
17:19:43    Got 35 results, configured to fail if != 0
17:19:43  
17:19:43    compiled Code at target/compiled/recurly_source/models/stg_recurly.yml/dbt_utils_unique_combination_o_0668cff24a63b94c64f5d150d5aeedd2.sql
17:19:43
```

### Expected behavior

I don't know exactly. Either the correct behavior for that model is it has duplicates, and the test should be removed, OR upstream the latest version of the row per id is chosen. I'm not clear enough on what the final models are intended to represent to say for sure, but I expect is the latter.

### dbt Project configurations

No special config here

### Package versions

  - package: fivetran/recurly
    version: 0.2.0

### What database are you using dbt with?

snowflake

### dbt Version

1.3.1

### Additional Context

I might be able to help with fixing this upon, but I'm unclear on what the final models are intended to represent.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment] 2023-02-10 22:45
Hi @DylanNWatt thanks for opening this issue and sorry you are seeing these failures.

A few things I wanted to clarify and confirm before moving forward:

We do include a test on the line_item_history staging model; however, we take into account that the source table has historical records and therefore test the uniqueness on the combination of `line_item_id` and `updated_at`. This should show us unique historical records. 

Expanding on the above, it looks like your models are not failing on the above test based on your error messages. Instead it looks like your tests are failing on the [recurly__balance_transactions](https://github.com/fivetran/dbt_recurly/blob/2da1316991d1498e85317150d2587c74ea358972/models/recurly.yml#L190-L197) test and the [stg_recurly__invoice_coupon_redemption_history](https://github.com/fivetran/dbt_recurly_source/blob/a35f9b1af26d43b615a849a58c055615cf4a1133/models/stg_recurly.yml#L205-L211) test. To best understand what may be going on here I would recommend querying these tables on the respective fields that are being tested for uniqueness:
- For the stg_recurly__invoice_coupon_redemption_history test failure
```sql
    select
        coupon_redemption_id, updated_at
    from stg_recurly__coupon_redemption_history
    group by coupon_redemption_id, updated_at
    having count(*) > 1
```
Once you run this, you should see 35 results. I would take one of those id and updated_at records and do a query on the staging table to determine if this truly is a duplicate. If all the fields are the same, then I would assume this to be a true duplicate and needs to be resolved within the source. If not, then this may be something we need to adjust in the package.

- For the recurly__balance_transactions test failure
```sql
with dbt_test__target as (

  select balance_transaction_id
  from recurly__balance_transactions
  where balance_transaction_id is not null

)

select
    balance_transaction_id,
    count(*) as n_records

from dbt_test__target
group by unique_field
having count(*) > 1
```
Similar to the above, I would then expect to see 717 results from this query. I would then take one of these `balance_transaction_id` and inspect this id in the stg_recurly__line_item_history staging model. If you you see that this field has true duplicates then I would assume this to be something that needs to be sorted out in the source. Otherwise, we can explore any modifications needed to the package.

I do want to call out that in the recurly__balance_transactions end model, we do [filter for only active records](https://github.com/fivetran/dbt_recurly/blob/2da1316991d1498e85317150d2587c74ea358972/models/recurly__balance_transactions.sql#L1-L6). This is making me a bit suspicious that these may be true duplicates. Regardless, running the operations above will definitely help us get to the bottom of the issue!

Let me know if you have any questions!

**Comment by DylanNWatt** [comment] 2023-02-13 20:46
Hi, for the sql for  `stg_recurly__invoice_coupon_redemption_history` I assume the SQL should reference that table and not `stg_recurly__coupon_redemption_history`? 

If so, this looks like legit data, because coupon updated IDs are 1:many with invoice ids. I don't think these IDs are particularly sensitive data, so here: 
<img width="867" alt="image" src="https://user-images.githubusercontent.com/1738085/218569919-df99b195-3d73-468c-837e-f42ad9e315d1.png">

Similarly for balance_transaction_ids:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/1738085/218570663-34d4f58f-82ee-4ab9-82ac-70681c752c92.png">

So for both of these, it appears the source intentionally has these IDs duplicated, one for 1:many, the other maybe for history logging?

**Comment by fivetran-joemarkiewicz** [comment] 2023-02-15 20:18
Hi @DylanNWatt thanks for sharing this additional information. Unfortunately, I am still having a hard time determining what may be causing the test failures for you. Even though you are showing the duplicate IDs, our tests should take into account the `is_most_recent_record` boolean and not flag them as dupes since they are historical.

I feel the only way we will be able to get to the bottom of this is if you are able to schedule some time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2023-02) for us to debug together live.

**Comment by DylanNWatt** [comment] 2023-02-15 21:06
Done, set time for next wednesdau.

**Comment by fivetran-avinash** [comment] 2023-02-23 00:38
Hey @DylanNWatt! Thanks again for taking the time out today to debug these test failures with us live. It's super critical for us to see what customers are seeing and this should hopefully help us. 

For creating a PR on `dbt_recurly_source`, Instructions on how to contribute to the package  [are here.](
https://discourse.getdbt.com/t/contributing-to-a-dbt-package/657)  You'll need to fork the repo and open a PR off the forked changes you make!

Please let us know if you have any questions! We're happy to assist.

**Comment by benigls** [comment] 2023-03-02 10:23
Hi @DylanNWatt @fivetran-avinash 👋🏼 

I also got a test failure for `dbt_utils_unique_combination_of_columns_stg_recurly__invoice_coupon_redemption_history_coupon_redemption_id__invoice_updated_at`, did you manage to find the root cause?

**Comment by fivetran-avinash** [comment] 2023-03-02 19:51
HI @benigls yep we believe we have found the issue for both of these test failures.

For `dbt_utils_unique_combination_of_columns_stg_recurly__invoice_coupon_redemption_history_coupon_redemption_id__invoice_updated_at`, we will need to add `invoice_id` into the combination of columns. 

For `unique_recurly__balance_transactions_balance_transaction_id` (I see you opened up an issue there too), we plan on adding a `unique_combination_of_columns` for `transaction_id`, which appears to provide uniqueness.
 
@DylanNWatt and I are working to create a PR to hopefully fix these issues shortly.

**Comment by fivetran-avinash** [comment] 2023-03-03 00:34
Hey @DylanNWatt, just wanted to check in and see if you'll have time to create a PR for this issue. Otherwise we will fold this task into our next sprint next week. Let us know if you need any assistance!

**Comment by fivetran-avinash** [comment] 2023-03-21 22:28
Hi @DylanNWatt and @benigls, we've deployed these latest test fixes to our packages in our latest releases to both packages ([dbt_recurly](https://github.com/fivetran/dbt_recurly/releases/tag/v0.3.2) & [dbt_recurly_source](https://github.com/fivetran/dbt_recurly_source/releases/tag/v0.2.1)). Try it out and let us know what you think!

**Closed** 2023-03-22 17:44 UTC
Labels: priority:p2, type:bug, status:in_progress, update_type:testing

**Comment by benigls** [comment] 2023-03-23 07:38
Thanks @fivetran-avinash 🙏🏼 I'll check it out
